<?php

namespace App\Services;

use App\Models\Prescription;

class PrescriptionPdfService
{
    public function render(Prescription $prescription): string
    {
        $prescription->load(['appointment.clinic', 'doctor.user', 'doctor.specialization', 'patient', 'items']);

        $lines = [
            'MediQueue Digital Prescription',
            ' ',
            'Prescription ID: '.$prescription->id,
            'Issued At: '.$prescription->issued_at?->format('d M Y, h:i A'),
            'Clinic: '.$prescription->appointment->clinic->name,
            'Doctor: Dr. '.$prescription->doctor->user->name.' - '.$prescription->doctor->specialization->name,
            'Patient: '.$prescription->patient->name,
            ' ',
            'Diagnosis:',
            $prescription->diagnosis,
            ' ',
            'Medicines:',
        ];

        foreach ($prescription->items as $index => $item) {
            $lines[] = ($index + 1).'. '.$item->medicine_name.' | '.$item->dosage.' | '.$item->frequency.' | '.$item->duration;
        }

        $lines[] = ' ';
        $lines[] = 'Notes: '.($prescription->notes ?: 'N/A');
        $lines[] = ' ';
        $lines[] = 'Generated by MediQueue Smart Clinic SaaS';

        $content = "BT\n/F1 11 Tf\n50 780 Td\n";

        foreach ($lines as $index => $line) {
            $safeLine = $this->escapePdfText($line);
            $content .= $index === 0 ? "({$safeLine}) Tj\n" : "0 -18 Td\n({$safeLine}) Tj\n";
        }

        $content .= "ET";

        $objects = [
            "1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n",
            "2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n",
            "3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>\nendobj\n",
            "4 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n",
            "5 0 obj\n<< /Length ".strlen($content)." >>\nstream\n{$content}\nendstream\nendobj\n",
        ];

        $pdf = "%PDF-1.4\n";
        $offsets = [0];

        foreach ($objects as $object) {
            $offsets[] = strlen($pdf);
            $pdf .= $object;
        }

        $xrefOffset = strlen($pdf);
        $pdf .= "xref\n0 ".(count($objects) + 1)."\n";
        $pdf .= "0000000000 65535 f \n";

        for ($i = 1; $i <= count($objects); $i++) {
            $pdf .= sprintf("%010d 00000 n \n", $offsets[$i]);
        }

        $pdf .= "trailer\n<< /Size ".(count($objects) + 1)." /Root 1 0 R >>\n";
        $pdf .= "startxref\n{$xrefOffset}\n%%EOF";

        return $pdf;
    }

    private function escapePdfText(string $text): string
    {
        $asciiText = iconv('UTF-8', 'ASCII//TRANSLIT//IGNORE', $text);
        $normalized = preg_replace('/[^\x20-\x7E]/', '', $asciiText !== false ? $asciiText : $text) ?? '';

        return str_replace(['\\', '(', ')'], ['\\\\', '\\(', '\\)'], $normalized);
    }
}
